Repository ministryofjustice/offender-categorisation, pull requests merged in 2022-05, with the labels that each got.

#532 DSE-161: Upgraded HMPPS Orb from 3.14 to 5.1
  .circleci/config.yml
Labels: dependencies

#531 DSE-67: added #main-content width rule to fit content to fix table UI
  assets/sass/local.sass
Labels: bug

#533 [DSE-132] Added alerts to dps_sed_alerts
  .circleci/config.yml
Labels: enhancement
